### ISSUE TITLE
DSN not supporting special chars

### ISSUE THREAD

**Issue by majandres** [coroot/coroot-pg-agent#13]
When setting the DSN, if a password contains some characters such as `|` or `@`, then a parse error is received

`1 collector.go:123] parse "postgresql://user:<**redacted**>@<**redacted**>5432/<**redacted**>?connect_timeout=1&statement_timeout=30000": net/url: invalid userinfo
`

**Comment by apetruhin** [comment]
@majandres, a password should be [urlencoded](https://en.wikipedia.org/wiki/URL_encoding), if it contains special characters like `space`, `@`, `|`, `/`, etc.

A sample docker-python one-liner:
```bash
$ docker run -it --rm python:3 python -c "import urllib.parse; print(urllib.parse.quote_plus('pwd@123'))"
pwd%40123
```

So, the DSN should look like:
```
postgresql://coroot:pwd%40123@127.0.0.1:5432/postgres?connect_timeout=1&statement_timeout=30000
```
