### ISSUE TITLE
One Agent Can monitor multiple pg instances?

### ISSUE THREAD

**Issue by tripitakav** [coroot/coroot-pg-agent#14]
We have multiple pg instance，if one agent can monitor multiple pg instances，it will be very practical！

**Comment by apetruhin** [comment]
@tripitakav, unfortunately no, pg-agent is designed to monitor a single Postgres instance.
We've followed the Prometheus [guideline](https://prometheus.io/docs/instrumenting/writing_exporters/#deployment) that recommends "each exporter to monitor exactly one instance of an application".

**Comment by tripitakav** [comment]
> @tripitakav, unfortunately no, pg-agent is designed to monitor a single Postgres instance. We've followed the Prometheus [guideline](https://prometheus.io/docs/instrumenting/writing_exporters/#deployment) that recommends "each exporter to monitor exactly one instance of an application".

ok，thanks
