### ISSUE TITLE
Adding a static label

### ISSUE THREAD

**Issue by mauza** [coroot/coroot-pg-agent#4]
We'd like to add these agents to every cloud sql instance in our gcp project. It is working well on one instance, but the "instance" label that is surfaced is just the IP address of the deployed pg-agent pod. It would be nicer and cleaner if we could add our own label that we could reference that would be the name of the sql instance the pg-agent is connected to. It seems like it would be fairly simple to add the ability in environment variables or otherwise to add a few static labels if needed/wanted.

**Comment by def** [comment]
From version 1.0.9 you can add multiple `--label` arguments, e.g. `--label="key1:value1" --label="key2:value2"` or set the `STATIC_LABELS` environment variable with a newline-separated list of labels.
